export const FORM_LOGIN_REQUEST = "FORM_LOGIN_REQUEST";
export const FORM_LOGIN_SUCCESS = "FORM_LOGIN_SUCCESS";
export const FORM_LOGIN_FAIL = "FORM_LOGIN_FAIL";
export const OAUTH_LOGIN_REQUEST = "OAUTH_LOGIN_REQUEST";
export const OAUTH_LOGIN_SUCCESS = "OAUTH_LOGIN_SUCCESS";
export const OAUTH_LOGIN_FAIL = "OAUTH_LOGIN_FAIL";

export const FORM_REGISTER_REQUEST = "FORM_REGISTER_REQUEST";
export const FORM_REGISTER_SUCCESS = "FORM_REGISTER_SUCCESS";
export const FORM_REGISTER_FAIL = "FORM_REGISTER_FAIL";
export const OAUTH_REGISTER_REQUEST = "OAUTH_REGISTER_REQUEST";
export const OAUTH_REGISTER_SUCCESS = "OAUTH_REGISTER_SUCCESS";
export const OAUTH_REGISTER_FAIL = "OAUTH_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
