export const ADD_ITEM_GUEST_SUCCESS = "ADD_ITEM_GUEST_SUCCESS";
export const ADD_ITEM_GUEST_FAIL = "ADD_ITEM_GUEST_FAIL";

export const REMOVE_ITEM_GUEST_SUCCESS = "REMOVE_ITEM_GUEST_SUCCESS";
export const REMOVE_ITEM_GUEST_FAIL = "REMOVE_ITEM_GUEST_FAIL";

export const ADD_ITEM_USER_SUCCESS = "ADD_ITEM_USER_SUCCESS";
export const ADD_ITEM_USER_FAIL = "ADD_ITEM_USER_FAIL";

export const REMOVE_ITEM_USER_SUCCESS = "REMOVE_ITEM_USER_SUCCESS";
export const REMOVE_ITEM_USER_FAIL = "REMOVE_ITEM_USER_FAIL";

export const GET_CARTITEMS_USER_SUCCESS = "GET_CARTITEMS_USER_SUCCESS";
export const GET_CARTITEMS_USER_FAIL = "GET_CARTITEMS_USER_FAIL";

export const OAUTH_UPDATE_CART_SUCCESS = "OAUTH_UPDATE_CART_SUCCESS";
export const OAUTH_UPDATE_CART_FAIL = "OAUTH_UPDATE_CART_FAIL";

export const EMPTY_CART = "EMPTY_CART";