export const COLLECTIONS_LIST_REQUEST = "COLLECTIONS_LIST_REQUEST";
export const COLLECTIONS_LIST_SUCCESS = "COLLECTIONS_LIST_SUCCESS";
export const COLLECTIONS_LIST_FAIL = "COLLECTIONS_LIST_FAIL";

export const NEW_COLLECTION_SUCCESS = "NEW_COLLECTION_SUCCESS";
export const NEW_COLLECTION_FAIL = "NEW_COLLECTION_FAIL";

export const NAME_UPDATE_FAIL = "NAME_UPDATE_FAIL";
export const NAME_UPDATE_SUCCESS = "NAME_UPDATE_SUCCESS";

export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAIL = "DELETE_COLLECTION_FAIL";