export const FETCH_USER_ORDERS_REQUEST = "FETCH_USER_ORDERS_REQUEST";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_FAIL = "FETCH_USER_ORDERS_FAIL";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

export const EDIT_ORDER_REQUEST = "EDIT_ORDER_REQUEST";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_FAIL = "EDIT_ORDER_FAIL";

//admin
export const FILTER_PERIOD_REQUEST = "FILTER_PERIOD_REQUEST";
export const FILTER_PERIOD_SUCCESS = "FILTER_PERIOD_SUCCESS";
export const FILTER_PERIOD_FAIL = "FILTER_PERIOD_FAIL";

export const SEARCH_ORDER_REQUEST = "SEARCH_ORDER_REQUEST";
export const SEARCH_ORDER_SUCCESS = "SEARCH_ORDER_SUCCESS";
export const SEARCH_ORDER_FAIL = "SEARCH_ORDER_FAIL";
