export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAIL = "FETCH_REVIEWS_FAIL";

export const CLEAR_REVIEWS = "CLEAR_REVIEWS";

export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const MODERATE_REVIEW_SUCCESS = "MODERATE_REVIEW_SUCCESS";
export const MODERATE_REVIEW_FAIL = "MODERATE_REVIEW_FAIL";

export const EDIT_REVIEW_FAIL = "EDIT_REVIEW_FAIL";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
