export const FILTERED_PRODUCTS_REQUEST = "SHOP_PRODUCTS_REQUEST";
export const FILTERED_PRODUCTS_SUCCESS = "SHOP_PRODUCTS_SUCCESS";
export const FILTERED_PRODUCTS_FAIL = "SHOP_PRODUCTS_FAIL";

export const SHOP_COLLECTION_REQUEST = "SHOP_COLLECTION_REQUEST";
export const SHOP_COLLECTION_SUCCESS = "SHOP_COLLECTION_SUCCESS";
export const SHOP_COLLECTION_FAIL = "SHOP_COLLECTION_FAIL";