export const COLLECTIONS_LIST_REQUEST = "COLLECTIONS_LIST_REQUEST";
export const COLLECTIONS_LIST_SUCCESS = "COLLECTIONS_LIST_SUCCESS";
export const COLLECTIONS_LIST_FAIL = "COLLECTIONS_LIST_FAIL";

export const NEW_COLLECTION_REQUEST = "NEW_COLLECTION_REQUEST";
export const NEW_COLLECTION_SUCCESS = "NEW_COLLECTION_SUCCESS";
export const NEW_COLLECTION_FAIL = "NEW_COLLECTION_FAIL";

export const DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAIL = "DELETE_COLLECTION_FAIL";

export const COLLECTION_EDIT_REQUEST = "COLLECTION_EDIT_REQUEST";
export const COLLECTION_EDIT_SUCCESS = "COLLECTION_EDIT_SUCCESS";
export const COLLECTION_EDIT_FAIL = "COLLECTION_EDIT_FAIL";

export const FETCH_PEXEL_REQUEST = "FETCH_PEXEL_REQUEST";
export const FETCH_PEXEL_FAIL = "FETCH_PEXEL_FAIL";
export const FETCH_PEXEL_SUCCESS = "FETCH_PEXEL_SUCCESS";