export const SET_ISGUEST = "SET_ISGUEST";
export const SET_ITEMS = "SET_ITEMS";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_EMAIL_ADDRESS = "SET_EMAIL_ADDRESS";
export const SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const SET_ISCANCELLED = "SET_ISCANCELLED";
export const SET_ISPAID = "SET_ISPAID";
export const SET_ISSHIPPEDTOCOURIER = "SET_ISSHIPPEDTOCOURIER";
export const SET_ISDELIVERED = "SET_ISDELIVERED";
export const CLEAR_ORDER = "CLEAR_ORDER";

export const NEW_USER_ORDER_REQUEST = "NEW_USER_ORDER_REQUEST";
export const NEW_USER_ORDER_SUCCESS = "NEW_USER_ORDER_SUCCESS";
export const NEW_USER_ORDER_FAIL = "NEW_USER_ORDER_FAIL";
export const NEW_GUEST_ORDER_SUCCESS = "NEW_GUEST_ORDER_SUCCESS";
export const NEW_GUEST_ORDER_FAIL = "NEW_GUEST_ORDER_FAIL";





