const styles = {
  cardWrapper: {
    // width: "80%",
    width: "190px",
    height: "auto",
    // height: "auto",
    display: "flex",
    flexDirectinon: "column",
    // height: "200px",
    cursor: "pointer",
    justifyContent: "center",
    alignItems: "center",
    // background: "#e0e0e0",
    boxShadow: 3,
    borderRadius: "10px",
    margin: "5px",
  },
  cardImageWrapper: {
    position: "relative",
    padding: "0px",
    // margin: "10px",
    borderRadius: "10px",
    // border: "1px solid black",
    // border: "3px solid purple",
    width: "100%",
    height: "100%",
    transition: "transform .2s",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: "10px",
  },
  overlayBox: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    borderRadius: "10px",
    zIndex: 2,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    color: "white",
    padding: "8px",
    textAlign: "center",
  },
};

export default styles;
